export const theme = {
  colors: {
    white: "#ffffff",
    light: "#fefefe",
    lightbg: "#f6f8ff",
    darkblue: "#2b3442",
    darkSky: "#4b6a9b",
    dark: "#141d2f",
    semidark: "#1e2a47",
    gray: "#697c9a",
    electric: "#0079ff",
    semiBlack: "#222731",
  },
  lightMode: {
    bg: "#f6f8ff",
    title: "#222731",
    darkButton: "#4b6a9b",
    searchContainer: "#ffffff",
    buttonColor: "#ffffff",
    button: "#0079ff",
    searchDiv: "#ffffff",
    inputColor: "#222731",
    inputBg: "#ffffff",
    inputPlaceholder: "#1e2a47",
    maincardContainer: "#ffffff",
    name: "#2b3442",
    login: "#0079ff",
    date: "#697c9a",
    bio: "#1e2a47",
    statsBackground: "#f6f8ff",
    statsTitle: "#697c9a",
    statsText: "#2b3442",
    locationsP: "#1e2a47",
  },
  darkMode: {
    bg: "#141d2f",
    title: "#ffffff",
    darkButton: "#ffffff",
    searchContainer: "#1e2a47",
    buttonColor: "#ffffff",
    button: "#0079ff",
    searchDiv: "#1e2a47",
    inputColor: "#fefefe",
    inputBg: "#1e2a47",
    inputPlaceholder: "#fefefe",
    maincardContainer: "#1e2a47",
    name: "#ffffff",
    login: "#0079ff",
    date: "#ffffff",
    bio: "#ffffff",
    statsBackground: "#141d2f",
    statsTitle: "#ffffff",
    statsText: "#ffffff",
    locationsP: "#ffffff",
  },

  fonts: {
    primary: "'Space Mono', sans-serif",
  },
};
